import { Prose, H1, Lead, H2, P, UL, Mono, Callout, CodeBlock } from "@/components/docs/prose";
import { Toc } from "@/components/docs/toc";

export const metadata = { title: "PoolPass docs: Protocol 25/26 host functions" };

const PARITY_HASH = "115cc0f5e7d690413df64c6b9662e9cf2a3617f2743245519e19607a4417189a";
const GATE_A_TX = "94e5d8b1a6161bea6581b305c522981d2674ac87db49bc6263126d7b3167e4d5";
const GATE_B_TX = "593c2516f1c8b431a0ff8cf09a82ba92eb467bfb0e6f1b72099bfb25d0490ee1";

export default function HostFunctions() {
  return (
    <Prose>
      <H1>Protocol 25/26 host functions</H1>
      <Lead>
        PoolPass does no userland Poseidon and no userland BN254 arithmetic. Both route through native Soroban host
        functions shipped in Stellar Protocol 25 (X-Ray) and 26 (Yardstick). This is what makes on-chain ZK verification
        cheap enough to be practical.
      </Lead>

      <Toc />

      <H2 id="why">Why native host functions matter</H2>
      <P>
        A Groth16 verification is a handful of elliptic-curve pairings on BN254. Implemented in WASM, the pairings blow
        far past Soroban&rsquo;s CPU instruction budget. As native host functions, the same operations are a single
        priced host call. The two relevant capabilities:
      </P>
      <UL>
        <li>
          <strong>CAP-0074, BN254.</strong> Native BN254 curve operations and pairing, used by the Groth16 verifier.
        </li>
        <li>
          <strong>CAP-0075, Poseidon.</strong> Native Poseidon hashing over BN254 Fr, used for leaves, the Merkle tree,
          the nullifier, and the commitment.
        </li>
      </UL>
      <P>
        Every Poseidon hash in the PoolPass contract and the parity gate routes through <Mono>soroban-poseidon</Mono> to
        the native <Mono>soroban-sdk</Mono> host function. No contract in the repository contains a userland Poseidon or
        BN254 implementation.
      </P>

      <H2 id="gate-a">Gate A, Poseidon parity equality</H2>
      <P>
        The parity gate proves the on-chain Poseidon agrees, byte for byte, with the off-chain library and the Circom
        circuit. This is the single most important piece of evidence in these docs, reproduced verbatim from{" "}
        <Mono>docs/e2e-transcript.md</Mono>:
      </P>

      <Callout tone="proof" title="Gate A, Poseidon parity equality">
        <ul className="ml-lg list-disc space-y-xs">
          <li>
            Input pair, as BN254 Fr decimal strings: <Mono>&quot;1&quot;</Mono>, <Mono>&quot;2&quot;</Mono>.
          </li>
          <li>
            Off-chain library output: <Mono>{PARITY_HASH}</Mono>. Computed by the shared <Mono>merkle-tools/poseidon.js</Mono>{" "}
            path backed by <Mono>circomlibjs</Mono> 0.1.7.
          </li>
          <li>
            Circuit witness output: <Mono>{PARITY_HASH}</Mono>. Obtained from the witness generated by{" "}
            <Mono>circuits/gates/poseidon_pair.circom</Mono> for the same input pair.
          </li>
          <li>
            On-chain host output: <Mono>{PARITY_HASH}</Mono>. The Gate A contract returned this value for the forced
            testnet invocation{" "}
            <a className="text-primary hover:underline" href={`https://stellar.expert/explorer/testnet/tx/${GATE_A_TX}`} target="_blank" rel="noreferrer">
              {GATE_A_TX.slice(0, 6)}…{GATE_A_TX.slice(-4)}
            </a>
            .
          </li>
          <li>
            Assertion: all three 32-byte hex strings are byte-identical, confirming off-chain, Circom, and Soroban-host
            Poseidon parity.
          </li>
        </ul>
      </Callout>

      <P>
        The selected variant is classic circomlib Poseidon over BN254 Fr. Two-input hashing uses <Mono>t=3</Mono>,{" "}
        <Mono>R_F=8</Mono>, and <Mono>R_P=57</Mono>; three-input hashing uses <Mono>t=4</Mono>, <Mono>R_F=8</Mono>, and{" "}
        <Mono>R_P=56</Mono>.
      </P>

      <H2 id="gate-b">Gate B, native BN254 Groth16 verification</H2>
      <P>
        Gate B forces a native BN254 Groth16 verification on chain, proving the verifier path works against the host
        pairing function rather than a userland fallback:
      </P>
      <CodeBlock lang="testnet tx">{GATE_B_TX}</CodeBlock>
      <P>
        Verified invocation:{" "}
        <a className="text-primary hover:underline" href={`https://stellar.expert/explorer/testnet/tx/${GATE_B_TX}`} target="_blank" rel="noreferrer">
          {GATE_B_TX.slice(0, 6)}…{GATE_B_TX.slice(-4)}
        </a>
        .
      </P>
    </Prose>
  );
}
