[workspace]
resolver = "2"
members = ["contracts/gate-poseidon", "contracts/gate-groth16", "contracts/poolpass"]

[workspace.package]
edition = "2021"
rust-version = "1.91.0"
license = "Apache-2.0"

[workspace.dependencies]
soroban-sdk = { version = "=26.1.0", features = ["hazmat-crypto"] }
soroban-poseidon = "=26.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
