[package]
name = "gate-poseidon"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
soroban-sdk.workspace = true
soroban-poseidon.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
